diseases = {
    "asthma": "https://www.lung.org/lung-health-diseases/lung-disease-lookup/asthma",
    "heart disease": "https://www.heart.org/en/health-topics/heart-attack",
    "diabetes": "https://www.diabetes.org/",
    "hypertension": "https://www.heart.org/en/health-topics/high-blood-pressure",
    "stroke": "https://www.stroke.org/en/about-stroke",
    "cancer": "https://www.cancer.org/",
    "tuberculosis": "https://www.cdc.gov/tb/",
    "pneumonia": "https://www.lung.org/lung-health-diseases/lung-disease-lookup/pneumonia",
    "bronchitis": "https://www.lung.org/lung-health-diseases/lung-disease-lookup/bronchitis",
    "copd": "https://www.lung.org/lung-health-diseases/lung-disease-lookup/copd",
    "arthritis": "https://www.arthritis.org/",
    "migraine": "https://americanmigrainefoundation.org/",
    "anemia": "https://www.mayoclinic.org/diseases-conditions/anemia",
    "allergy": "https://www.aaaai.org/conditions-and-treatments/allergies",
    "obesity": "https://www.cdc.gov/obesity/",
    "epilepsy": "https://www.epilepsy.com/",
    "dementia": "https://www.alz.org/alzheimers-dementia",
    "autism": "https://www.autismspeaks.org/",
    "parkinson's disease": "https://www.parkinson.org/",
    "leukemia": "https://www.cancer.org/cancer/leukemia.html",
    "glaucoma": "https://www.glaucoma.org/",
    "hepatitis": "https://www.cdc.gov/hepatitis/",
    "kidney disease": "https://www.kidney.org/",
    "thyroid disorder": "https://www.thyroid.org/",
    "hiv/aids": "https://www.cdc.gov/hiv/",
    "dengue": "https://www.cdc.gov/dengue/",
    "malaria": "https://www.cdc.gov/malaria/",
    "covid-19": "https://www.cdc.gov/coronavirus/2019-ncov/",
    "unknown": "https://google.com"
}
