diseases = {
    "tumor": "https://www.cancer.gov/about-cancer/diagnosis-staging/tumors",
    "heart": "https://www.heart.org/en/health-topics/heart-attack",
    "diabetes": "https://www.diabetes.org/",
    "cancer": "https://www.cancer.org/",
    "hypertension": "https://www.heart.org/en/health-topics/high-blood-pressure",
    "stroke": "https://www.stroke.org/en/about-stroke",
    "asthma": "https://www.lung.org/lung-health-diseases/lung-disease-lookup/asthma",
    "arthritis": "https://www.arthritis.org/",
    "migraine": "https://americanmigrainefoundation.org/",
    "depression": "https://www.nimh.nih.gov/health/topics/depression",
    "anemia": "https://www.mayoclinic.org/diseases-conditions/anemia",
    "allergy": "https://www.aaaai.org/conditions-and-treatments/allergies",
    "bronchitis": "https://www.lung.org/lung-health-diseases/lung-disease-lookup/bronchitis",
    "pneumonia": "https://www.lung.org/lung-health-diseases/lung-disease-lookup/pneumonia",
    "obesity": "https://www.cdc.gov/obesity/",
    "epilepsy": "https://www.epilepsy.com/",
    "dementia": "https://www.alz.org/alzheimers-dementia",
    "autism": "https://www.autismspeaks.org/",
    "parkinson": "https://www.parkinson.org/",
    "leukemia": "https://www.cancer.org/cancer/leukemia.html",
    "glaucoma": "https://www.glaucoma.org/",
    "sclerosis": "https://www.nationalmssociety.org/",
    "hepatitis": "https://www.cdc.gov/hepatitis/",
    "kidney": "https://www.kidney.org/",
    "thyroid": "https://www.thyroid.org/",
    "HIV" : "https://www.cdc.gov/hiv/",
    "AIDS": "https://www.cdc.gov/hiv/",
    "malaria": "https://www.cdc.gov/malaria/",
    "tuberculosis": "https://www.cdc.gov/tb/",
    "chickenpox": "https://www.cdc.gov/chickenpox/",
    "covid19": "https://www.cdc.gov/coronavirus/2019-ncov/",
    "influenza": "https://www.cdc.gov/flu/",
    "smallpox": "https://www.cdc.gov/smallpox/",
    "measles": "https://www.cdc.gov/measles/",
    "polio": "https://www.cdc.gov/polio/",
    "cholera": "https://www.cdc.gov/cholera/",
    "botulism": "https://www.cdc.gov/botulism/",
    "lyme disease": "https://www.cdc.gov/lyme/",
    "dengue": "https://www.cdc.gov/dengue/",
    "zika virus": "https://www.cdc.gov/zika/",
    "hantavirus": "https://www.cdc.gov/hantavirus/",
    "ebola": "https://www.cdc.gov/vhf/ebola/",
    "marburg virus": "https://www.cdc.gov/vhf/marburg/",
    "West Nile Virus": "https://www.cdc.gov/westnile/",
    "SARS": "https://www.cdc.gov/sars/",
    "MERS": "https://www.cdc.gov/coronavirus/mers/",
    "E. coli infection": "https://www.cdc.gov/ecoli/",
    "salmonella": "https://www.cdc.gov/salmonella/",
    "hepatitis A": "https://www.cdc.gov/hepatitis/a/",
    "hepatitis B": "https://www.cdc.gov/hepatitis/b/",
    "hepatitis C": "https://www.cdc.gov/hepatitis/c/",
    "lupus": "https://www.lupus.org/",
    "epidemic keratoconjunctivitis": "https://www.cdc.gov/keratoconjunctivitis/",
    "scarlet fever": "https://www.cdc.gov/scarlet-fever/",
    "tetanus": "https://www.cdc.gov/tetanus/",
    "whooping cough": "https://www.cdc.gov/pertussis/",
    "chronic fatigue syndrome": "https://www.cdc.gov/cfs/",
    "tinnitus": "https://www.cdc.gov/tinnitus/",
    "hyperthyroidism": "https://www.thyroid.org/hyperthyroidism/",
    "hypothyroidism": "https://www.thyroid.org/hypothyroidism/",
    "liver cancer": "https://www.cancer.org/cancer/liver-cancer.html",
    "pancreatic cancer": "https://www.cancer.org/cancer/pancreatic-cancer.html",
    "brain cancer": "https://www.cancer.org/cancer/brain-cancer.html",
    "lung cancer": "https://www.cancer.org/cancer/lung-cancer.html",
    "skin cancer": "https://www.cancer.org/cancer/skin-cancer.html",
    "colon cancer": "https://www.cancer.org/cancer/colon-cancer.html",
    "bladder cancer": "https://www.cancer.org/cancer/bladder-cancer.html",
    "prostate cancer": "https://www.cancer.org/cancer/prostate-cancer.html",
    "stomach cancer": "https://www.cancer.org/cancer/stomach-cancer.html",
    "testicular cancer": "https://www.cancer.org/cancer/testicular-cancer.html",
    "breast cancer": "https://www.cancer.org/cancer/breast-cancer.html",
    "cervical cancer": "https://www.cancer.org/cancer/cervical-cancer.html",
    "esophageal cancer": "https://www.cancer.org/cancer/esophageal-cancer.html",
    "uterine cancer": "https://www.cancer.org/cancer/uterine-cancer.html",
    "ovarian cancer": "https://www.cancer.org/cancer/ovarian-cancer.html",
    "liver cirrhosis": "https://www.mayoclinic.org/diseases-conditions/cirrhosis/",
    "gallstones": "https://www.mayoclinic.org/diseases-conditions/gallstones/",
    "chronic bronchitis": "https://www.lung.org/lung-health-diseases/lung-disease-lookup/chronic-bronchitis",
    "COPD": "https://www.lung.org/lung-health-diseases/lung-disease-lookup/copd",
    "pulmonary fibrosis": "https://www.lung.org/lung-health-diseases/lung-disease-lookup/pulmonary-fibrosis",
    "pneumonitis": "https://www.lung.org/lung-health-diseases/lung-disease-lookup/pneumonitis",
    "eczema": "https://www.aafa.org/eczema/",
    "psoriasis": "https://www.psoriasis.org/",
    "rosacea": "https://www.aad.org/public/diseases/rosacea",
    "vitiligo": "https://www.aad.org/public/diseases/vitiligo",
    "acne": "https://www.aad.org/public/diseases/acne",
    "melanoma": "https://www.cancer.org/cancer/melanoma-skin-cancer.html",
    "actinic keratosis": "https://www.aad.org/public/diseases/actinic-keratosis",
    "shingles": "https://www.cdc.gov/shingles/",
    "chronic pain": "https://www.apa.org/news/press/releases/2018/08/chronic-pain",
    "fibromyalgia": "https://www.fmaware.org/",
    "rheumatoid arthritis": "https://www.arthritis.org/diseases/rheumatoid-arthritis",
    "osteoporosis": "https://www.niams.nih.gov/health-topics/osteoporosis",
    "gout": "https://www.arthritis.org/diseases/gout",
    "scleroderma": "https://www.scleroderma.org/",
    "amyotrophic lateral sclerosis": "https://www.als.org/",
    "multiple sclerosis": "https://www.nationalmssociety.org/",
    "muscular dystrophy": "https://www.mda.org/",
    "Parkinson's disease": "https://www.parkinson.org/",
    "Huntington's disease": "https://www.hdfoundation.org/",
    "Alzheimer's disease": "https://www.alz.org",
     "epilepsy": "https://www.epilepsy.com/",
    "stroke": "https://www.stroke.org/en/about-stroke",
    "dementia": "https://www.alz.org/alzheimers-dementia",
    
    "dengue": "https://www.cdc.gov/dengue/",
    "dengue fever": "https://www.cdc.gov/dengue/",
    "tuberculosis": "https://www.cdc.gov/tb/",
    "typhoid": "https://www.cdc.gov/typhoid-fever/",
    "cholera": "https://www.cdc.gov/cholera/",
    "malaria": "https://www.cdc.gov/malaria/",
    "measles": "https://www.cdc.gov/measles/",
    
    "herpes": "https://www.cdc.gov/herpes/",
    "herpes simplex": "https://www.cdc.gov/herpes/",
    "herpes zoster": "https://www.cdc.gov/shingles/",
    
    "chronic fatigue syndrome": "https://www.cdc.gov/cfs/",
    "fibromyalgia": "https://www.fmaware.org/",
    "sleep apnea": "https://www.cdc.gov/sleepapnea/",
    "narcolepsy": "https://www.ninds.nih.gov/health-information/disorders/narcolepsy",
    "insomnia": "https://www.cdc.gov/sleep/",
    
    "meningitis": "https://www.cdc.gov/meningitis/",
    "encephalitis": "https://www.cdc.gov/encephalitis/",
    "brain abscess": "https://www.cdc.gov/brain-abscess/",
    "spinal cord infection": "https://www.cdc.gov/spinal-cord-infections/",
    
    "polio": "https://www.cdc.gov/polio/",
    "poliomyelitis": "https://www.cdc.gov/polio/",
    "Guillain-Barré syndrome": "https://www.ninds.nih.gov/health-information/disorders/gbs",
    "toxoplasmosis": "https://www.cdc.gov/parasites/toxoplasmosis/",
    "pericarditis": "https://www.heart.org/en/health-topics/pericarditis",
    "sjogren’s syndrome": "https://www.niams.nih.gov/health-topics/sjogrens-syndrome",
    "trigeminal neuralgia": "https://www.ninds.nih.gov/health-information/disorders/trigeminal-neuralgia",
    "rectal cancer": "https://www.cancer.org/cancer/colon-rectal-cancer.html",
    "pemphigus vulgaris": "https://www.aad.org/public/diseases/a-z/pemphigus-vulgaris",
    "sinus cancer": "https://www.cancer.org/cancer/nasal-cavity-and-paranasal-sinuses-cancer.html",
    "barrett's esophagus": "https://www.cancer.org/cancer/esophagus-cancer/about/what-is-barretts-esophagus.html",
    "wilson's disease": "https://www.niddk.nih.gov/health-information/liver-disease/wilsons-disease",
    "tachycardia": "https://www.heart.org/en/health-topics/arrhythmia/about-arrhythmia/tachycardia---fast-heart-rate",
    "bradycardia": "https://www.heart.org/en/health-topics/arrhythmia/about-arrhythmia/bradycardia---slow-heart-rate",
    "endometriosis": "https://www.cdc.gov/reproductivehealth/conditions/endometriosis.htm",
    "interstitial cystitis": "https://www.niddk.nih.gov/health-information/urologic-diseases/interstitial-cystitis",
    "myasthenia gravis": "https://www.ninds.nih.gov/health-information/disorders/myasthenia-gravis",
    "guillain-barre syndrome": "https://www.ninds.nih.gov/health-information/disorders/guillain-barre-syndrome",
    "churg-strauss syndrome": "https://rarediseases.info.nih.gov/diseases/7110/eosinophilic-granulomatosis-with-polyangiitis",
    "aspergillosis": "https://www.cdc.gov/fungal/diseases/aspergillosis/index.html",
    "histoplasmosis": "https://www.cdc.gov/fungal/diseases/histoplasmosis/index.html",
    "blastomycosis": "https://www.cdc.gov/fungal/diseases/blastomycosis/index.html",
    "coccidioidomycosis": "https://www.cdc.gov/fungal/diseases/coccidioidomycosis/index.html",
    "actinomycosis": "https://www.cdc.gov/actinomycosis/index.html",
    "cryptococcosis": "https://www.cdc.gov/fungal/diseases/cryptococcosis-neoformans/index.html",
    "toxocariasis": "https://www.cdc.gov/parasites/toxocariasis/",
    "trichinosis": "https://www.cdc.gov/parasites/trichinellosis/",
    "strongyloidiasis": "https://www.cdc.gov/parasites/strongyloides/",
    "giardiasis": "https://www.cdc.gov/parasites/giardia/",
    "amebiasis": "https://www.cdc.gov/parasites/amebiasis/",
    "ascariasis": "https://www.cdc.gov/parasites/ascariasis/",
    "hookworm": "https://www.cdc.gov/parasites/hookworm/",
    "pinworm": "https://www.cdc.gov/parasites/pinworm/",
    "schistosomiasis": "https://www.cdc.gov/parasites/schistosomiasis/",
    "echinococcosis": "https://www.cdc.gov/parasites/echinococcosis/",
    "leishmaniasis": "https://www.cdc.gov/parasites/leishmaniasis/",
    "chagas disease": "https://www.cdc.gov/parasites/chagas/",
    "babesiosis": "https://www.cdc.gov/parasites/babesiosis/",
    "toxoplasma encephalitis": "https://www.cdc.gov/parasites/toxoplasmosis/gen_info/faqs.html",
    "pityriasis rosea": "https://www.aad.org/public/diseases/rashes/pityriasis-rosea",
    "lichen planus": "https://www.aad.org/public/diseases/a-z/lichen-planus",
    "hidradenitis suppurativa": "https://www.aad.org/public/diseases/a-z/hidradenitis-suppurativa",
    "dermatomyositis": "https://www.niams.nih.gov/health-topics/dermatomyositis",
    "vitreous hemorrhage": "https://www.aao.org/eye-health/diseases/what-is-vitreous-hemorrhage",
    "retinal detachment": "https://www.nei.nih.gov/learn-about-eye-health/eye-conditions-and-diseases/retinal-detachment",
    "uveitis": "https://www.nei.nih.gov/learn-about-eye-health/eye-conditions-and-diseases/uveitis",
    "optic neuritis": "https://www.aao.org/eye-health/diseases/what-is-optic-neuritis",
    "macular degeneration": "https://www.nei.nih.gov/learn-about-eye-health/eye-conditions-and-diseases/age-related-macular-degeneration",
    "retinitis pigmentosa": "https://www.nei.nih.gov/learn-about-eye-health/eye-conditions-and-diseases/retinitis-pigmentosa",
    "keratitis": "https://www.cdc.gov/contactlenses/keratitis.html",
    "chalazion": "https://www.aao.org/eye-health/diseases/what-is-chalazion",
    "blepharitis": "https://www.aao.org/eye-health/diseases/what-is-blepharitis",
    "dacryocystitis": "https://www.aao.org/eye-health/diseases/dacryocystitis",
    "orbital cellulitis": "https://www.aao.org/eye-health/diseases/orbital-cellulitis",
    "corneal ulcer": "https://www.aao.org/eye-health/diseases/corneal-ulcer",
    "amblyopia": "https://www.nei.nih.gov/learn-about-eye-health/eye-conditions-and-diseases/amblyopia",
    "strabismus": "https://www.nei.nih.gov/learn-about-eye-health/eye-conditions-and-diseases/strabismus",
    "nystagmus": "https://www.nei.nih.gov/learn-about-eye-health/eye-conditions-and-diseases/nystagmus",
    "retinopathy of prematurity": "https://www.nei.nih.gov/learn-about-eye-health/eye-conditions-and-diseases/retinopathy-prematurity",
    "keratoconus": "https://www.nei.nih.gov/learn-about-eye-health/eye-conditions-and-diseases/keratoconus",
    "aniridia": "https://www.nei.nih.gov/learn-about-eye-health/eye-conditions-and-diseases/aniridia",
    "achromatopsia": "https://rarediseases.info.nih.gov/diseases/5/achromatopsia",
    "cone-rod dystrophy": "https://rarediseases.info.nih.gov/diseases/2544/cone-rod-dystrophy",
    "epidermolysis bullosa": "https://www.niams.nih.gov/health-topics/epidermolysis-bullosa",
    "porphyria": "https://www.porphyriafoundation.org/for-patients/types-of-porphyria/",
    "neurofibromatosis": "https://www.ninds.nih.gov/health-information/disorders/neurofibromatosis",
    "tuberous sclerosis": "https://www.tsalliance.org/",
    "sturge-weber syndrome": "https://rarediseases.info.nih.gov/diseases/1026/sturge-weber-syndrome",
    "moebius syndrome": "https://rarediseases.info.nih.gov/diseases/7120/moebius-syndrome",
    "prader-willi syndrome": "https://www.pwsausa.org/",
    "angelman syndrome": "https://www.angelman.org/",
    "williams syndrome": "https://williams-syndrome.org/",
    "marfan syndrome": "https://www.marfan.org/",
    "ehlers-danlos syndrome": "https://www.ehlers-danlos.com/",
    "noonan syndrome": "https://www.genome.gov/Genetic-Disorders/Noonan-Syndrome",
    "bardet-biedl syndrome": "https://rarediseases.info.nih.gov/diseases/5797/bardet-biedl-syndrome",
    "alport syndrome": "https://www.kidney.org/atoz/content/alport",
    "gitelman syndrome": "https://rarediseases.info.nih.gov/diseases/6631/gitelman-syndrome",
    "bartter syndrome": "https://rarediseases.info.nih.gov/diseases/577/bartter-syndrome",
    "von hippel-lindau disease": "https://www.cancer.gov/types/kidney/patient/vhl-treatment-pdq",
    "familial adenomatous polyposis": "https://www.cancer.gov/types/colorectal/patient/fap-treatment-pdq",
    "lynch syndrome": "https://www.cancer.gov/types/colorectal/patient/lynch-syndrome-pdq",
    "brca mutation": "https://www.cancer.gov/about-cancer/causes-prevention/genetics/brca-fact-sheet",
    "retinoblastoma": "https://www.cancer.gov/types/eye/patient/retinoblastoma-treatment-pdq",
    "medulloblastoma": "https://www.cancer.gov/types/brain/patient/medulloblastoma-treatment-pdq",
    "ependymoma": "https://www.cancer.gov/types/brain/patient/ependymoma-treatment-pdq",
    "glioblastoma": "https://www.cancer.gov/types/brain/patient/adult-glioblastoma-treatment-pdq",
    "choroid plexus carcinoma": "https://www.cancer.gov/pediatric-adult-rare-tumor/rare-tumors/rare-central-nervous-system-tumors/choroid-plexus",
    "craniopharyngioma": "https://www.cancer.gov/types/brain/patient/craniopharyngioma-treatment-pdq",
    "unknown": "https://www.google.com/"
}

